function print_run_summary( ...
    modelName, numExp, numSimRunExp, ...
    trainSet, resultHeldOut, resultSimRun, ...
    useIndependentSimRunTest, independentEvalMode, ...
    usePreprocessing, useBlockCoverageSampling, ...
    blockLenSampling, numBlocksKeepSampling, ...
    nu, ny)

    if useBlockCoverageSampling
        samplingFlagStr = 'enabled';
    else
        samplingFlagStr = 'disabled';
    end

    if usePreprocessing
        preprocessingStr = 'Savitzky-Golay';
    else
        preprocessingStr = 'none';
    end

    extraInfo = sprintf([ ...
        'Regressor dimension : %d\n' ...
        'Training experiments: %d\n' ...
        'Independent sim exps: %d\n' ...
        'Independent sim test: %s\n' ...
        'Independent eval    : %s\n' ...
        'Output preprocessing: %s\n' ...
        'Train sampling      : %s\n' ...
        'Sampling block len  : %d\n' ...
        'Sampling #blocks    : %d\n' ...
        'Train rows before   : %d\n' ...
        'Train rows after    : %d\n' ...
        'Held-out one-step   : %.6f\n' ...
        'Held-out free-run   : %.6f\n'], ...
        size(trainSet.Xtr,2), ...
        numExp, ...
        numSimRunExp, ...
        string(useIndependentSimRunTest), ...
        independentEvalMode, ...
        preprocessingStr, ...
        samplingFlagStr, ...
        blockLenSampling, ...
        numBlocksKeepSampling, ...
        trainSet.numRowsBeforeSampling, ...
        trainSet.numRowsAfterSampling, ...
        resultHeldOut.fit1, ...
        resultHeldOut.fitFree);

    if ~isempty(resultSimRun)
        extraInfo = sprintf('%sIndependent one-step: %.6f\nIndependent free-run: %.6f\n', ...
            extraInfo, resultSimRun.fit1, resultSimRun.fitFree);
    end

    algoNameSummary = sprintf('GP-NARX multi-exp (%d train exp)', numExp);

    print_sysid_summary(modelName, algoNameSummary, nu, ny, extraInfo);
end